version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
    image: laravel_8
    container_name: laravel_8-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./src/:/var/www
    networks:
      - laravel_8

  db:
    image: mysql:5.7
    container_name: laravel_8-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - laravel_8

  nginx:
    image: nginx:alpine
    container_name: laravel_8-nginx
    restart: unless-stopped
    ports:
      - "1234:80"
    volumes:
      - ./src/:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - laravel_8

networks:
  laravel_8:
    driver: bridge
