version: '3.3'

services:
  nginx:
    image: nginx
    ports:
      - 7777:80
  fpm:
    build:
      context: .
      dockerfile: Fpm.Dockerfile
    volumes:
      - ./../:/var/www/project2-database
    links:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - 33061:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel